export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS';
export const CHANGE_APP_STATE = 'CHANGE_APP_STATE';
export const SET_PENDING_UPDATE_NOTICE = 'SET_PENDING_UPDATE_NOTICE';
export const CHECK_APP_VERSION_STATUS = 'CHECK_APP_VERSION_STATUS';
export const CHECK_APP_PERMISSION_STATUS = 'CHECK_APP_PERMISSION_STATUS';
